# print("안녕하세요."+"반갑습니다")
# print("안녕하세요"*5)  
# print("안녕하세요"+10) Error 문자열 + 숫자
# print("Hello:"[0])
# print("Hello:"[1])
# print("Hello:"[2])
# print("Hello:"[3])
# print("Hello:"[4])
# print("Hello"[-1])
# print("Hello"[-2])
# print("Hello"[-3])
# print("Hello"[-4])
# print("Hello"[-5])
# print("Hello"[1:3])
# print("Hello"[2:4])
# print("Hello"[:3])
# print("Hello"[1:3])
# print("Hello"[2:4])
# print("Hello"[2:])
# print("Hello"[100]) # Error out of index
# print(len("Hello"))